CREATE TABLE public.robot_events (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    event_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image_url TEXT NOT NULL,
    identification TEXT NOT NULL
);

CREATE TABLE public.robot_error_log (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.map_images (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    posX DOUBLE PRECISION NOT NULL,
    posY DOUBLE PRECISION NOT NULL,
    theta DOUBLE PRECISION NOT NULL
);